dofile(widgetPath .. "settings.lua")
dofile(widgetPath .. "functions.lua")
dofile(widgetPath .. "textbox.lua")
dofile(widgetPath .. "progressbar.lua")
dofile(widgetPath .. "wibox.lua")
dofile(widgetPath .. "timer.lua")
dofile(widgetPath .. "toggleWibox.lua")
dofile(widgetPath .. "keys.lua")

vicious.force({volText,volPB})
